<?php

namespace ContainerWsKg1Qt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CbRITflService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CbRITfl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CbRITfl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\EpisodeController::index' => ['privates', '.service_locator.aGjXrxG', 'get_ServiceLocator_AGjXrxGService', true],
            'App\\Controller\\EpisodeController::watched' => ['privates', '.service_locator.aGjXrxG', 'get_ServiceLocator_AGjXrxGService', true],
            'App\\Controller\\LoginController::index' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.V6D1oJY', 'get_ServiceLocator_V6D1oJYService', true],
            'App\\Controller\\SeasonController::index' => ['privates', '.service_locator.KaU7cKq', 'get_ServiceLocator_KaU7cKqService', true],
            'App\\Controller\\SeriesController::edit' => ['privates', '.service_locator.KaU7cKq', 'get_ServiceLocator_KaU7cKqService', true],
            'App\\Controller\\SeriesController::update' => ['privates', '.service_locator.KaU7cKq', 'get_ServiceLocator_KaU7cKqService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\EpisodeController:index' => ['privates', '.service_locator.aGjXrxG', 'get_ServiceLocator_AGjXrxGService', true],
            'App\\Controller\\EpisodeController:watched' => ['privates', '.service_locator.aGjXrxG', 'get_ServiceLocator_AGjXrxGService', true],
            'App\\Controller\\LoginController:index' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.V6D1oJY', 'get_ServiceLocator_V6D1oJYService', true],
            'App\\Controller\\SeasonController:index' => ['privates', '.service_locator.KaU7cKq', 'get_ServiceLocator_KaU7cKqService', true],
            'App\\Controller\\SeriesController:edit' => ['privates', '.service_locator.KaU7cKq', 'get_ServiceLocator_KaU7cKqService', true],
            'App\\Controller\\SeriesController:update' => ['privates', '.service_locator.KaU7cKq', 'get_ServiceLocator_KaU7cKqService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\EpisodeController::index' => '?',
            'App\\Controller\\EpisodeController::watched' => '?',
            'App\\Controller\\LoginController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SeasonController::index' => '?',
            'App\\Controller\\SeriesController::edit' => '?',
            'App\\Controller\\SeriesController::update' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\EpisodeController:index' => '?',
            'App\\Controller\\EpisodeController:watched' => '?',
            'App\\Controller\\LoginController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SeasonController:index' => '?',
            'App\\Controller\\SeriesController:edit' => '?',
            'App\\Controller\\SeriesController:update' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
