<?php

namespace ContainerMDdMr8b;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KaU7cKqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KaU7cKq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KaU7cKq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'serie' => ['privates', '.errored..service_locator.KaU7cKq.App\\Entity\\Serie', NULL, 'Cannot autowire service ".service_locator.KaU7cKq": it needs an instance of "App\\Entity\\Serie" but this type has been excluded in "config/services.yaml".'],
        ], [
            'serie' => 'App\\Entity\\Serie',
        ]);
    }
}
