<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWsKg1Qt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWsKg1Qt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWsKg1Qt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWsKg1Qt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWsKg1Qt\App_KernelDevDebugContainer([
    'container.build_hash' => 'WsKg1Qt',
    'container.build_id' => 'e3d09b96',
    'container.build_time' => 1704313555,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWsKg1Qt');
